#!/usr/bin/env python3
"""Goal handoff-reporter — deterministic session summary FROM the ledger (v1.45.0).

Closes the walkinglabs feature-list component «репортёр handoff»: the shift
report is GENERATED by the harness from .itd-memory/GOAL.json (+ unit events in
events.jsonl), not composed by the model from conversation memory. /handoff and
/session-save paste this output verbatim into their artifacts; the model may add
prose AROUND it but never replaces the numbers.

Report contents (all derived, zero free-text):
  - goal, status, progress N/M verified, backpressure (open units count)
  - state distribution
  - per-unit table: id / status / criterion / evidence
  - current unit + its verificationCommand (the receiving session's first move)
  - last unit events from events.jsonl (audit trail, actor included)

Ships inside the skill (skills/goal/scripts/). Stdlib only.

Usage:
  itd_goal_report.py [--goal PATH] [--events PATH] [--json] [--max-events N]

Exit codes: 0 report printed, 2 ledger missing/invalid.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

GOAL_DEFAULT = Path(".itd-memory") / "GOAL.json"
OPEN_STATUSES = ("pending", "in_progress", "blocked")
CRIT_MAX = 70
EVID_MAX = 60


def die(msg: str) -> None:
    print(f"ERROR: {msg}")
    sys.exit(2)


def clip(s: str, n: int) -> str:
    # Pipe escaping: criterion/evidence are free text and land in a Markdown
    # table row — an unescaped "|" would split the cell and break the table.
    s = (s or "").replace("\n", " ").replace("|", "\\|").strip()
    return s if len(s) <= n else s[: n - 1] + "…"


def load_events(path: Path, max_events: int) -> list[dict]:
    if not path.is_file():
        return []
    events: list[dict] = []
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                evt = json.loads(line)
            except Exception:
                continue
            if evt.get("type") == "unit":
                events.append(evt)
    except Exception:
        return []
    return events[-max_events:]


def build(goal: dict, events: list[dict]) -> dict:
    units = [u for u in (goal.get("units") or []) if isinstance(u, dict)]
    dist: dict[str, int] = {}
    for u in units:
        dist[u.get("status") or "?"] = dist.get(u.get("status") or "?", 0) + 1
    verified = dist.get("verified", 0)
    open_units = [u for u in units if u.get("status") in OPEN_STATUSES]
    current = next((u for u in units
                    if u.get("id") == (goal.get("currentUnitId") or "")), None)
    if current is None:
        current = next((u for u in units if u.get("status") == "in_progress"), None)
    next_pending = next((u for u in units if u.get("status") == "pending"), None)
    return {
        "goal": goal.get("goal") or "",
        "status": goal.get("status") or "",
        "unitsTotal": len(units),
        "unitsVerified": verified,
        "backpressure": len(open_units),
        "distribution": dist,
        "units": units,
        "currentUnit": current,
        "nextPending": next_pending,
        "events": events,
        "updatedAt": goal.get("updatedAt") or "",
    }


def render_markdown(r: dict) -> str:
    out: list[str] = []
    out.append(f"## Goal report — {r['unitsVerified']}/{r['unitsTotal']} юнитов verified"
               f" [{r['status']}]")
    out.append("")
    out.append(f"**Цель:** {r['goal']}")
    out.append(f"**Обратное давление:** {r['backpressure']} открытых юнитов"
               f" (0 = цель завершена){'' if r['backpressure'] else ' ✅'}")
    dist = ", ".join(f"{k}: {v}" for k, v in sorted(r["distribution"].items()))
    out.append(f"**Состояния:** {dist}  (updatedAt: {r['updatedAt']})")
    out.append("")
    out.append("| Юнит | Статус | Критерий | Evidence |")
    out.append("|---|---|---|---|")
    for u in r["units"]:
        evid = u.get("evidence") or u.get("blockedReason") or u.get("skippedReason") or "—"
        out.append(f"| {u.get('id')} | {u.get('status')} "
                   f"| {clip(u.get('criterion'), CRIT_MAX)} | {clip(evid, EVID_MAX)} |")
    out.append("")
    cur = r["currentUnit"]
    blocked = [u for u in r["units"] if u.get("status") == "blocked"]
    if cur is not None:
        out.append(f"**Текущий юнит:** `{cur.get('id')}` — {clip(cur.get('criterion'), CRIT_MAX)}")
        out.append(f"**Первое действие принимающей сессии:** прогнать "
                   f"`{cur.get('verificationCommand')}` (должен быть red), затем чинить до green.")
    elif r["nextPending"] is not None:
        np = r["nextPending"]
        out.append(f"**Следующий юнит:** `{np.get('id')}` — {clip(np.get('criterion'), CRIT_MAX)}"
                   f" (активировать: `itd_goal_verify.py --activate {np.get('id')}`)")
    elif blocked:
        # blocked units ARE open — the goal is NOT closeable, do not suggest it.
        reasons = "; ".join(f"`{u.get('id')}` — {clip(u.get('blockedReason'), EVID_MAX)}"
                            for u in blocked)
        out.append(f"**Все открытые юниты заблокированы:** {reasons}. "
                   f"Разблокировка: `itd_goal_verify.py --activate <id>`; "
                   "закрывать цель нельзя, пока блокеры не сняты.")
    else:
        out.append("**Открытых юнитов нет** — закрыть цель (`status: done`).")
    if r["events"]:
        out.append("")
        out.append("<details><summary>Последние unit-события (events.jsonl)</summary>")
        out.append("")
        for e in r["events"]:
            out.append(f"- {e.get('at')} [{e.get('actor')}] {e.get('name')}: "
                       f"{e.get('decision')} — {clip(e.get('evidence'), EVID_MAX)}")
        out.append("")
        out.append("</details>")
    return "\n".join(out)


def main() -> int:
    # Windows consoles default to cp125x — reconfigure so the Russian report
    # never raises UnicodeEncodeError (platform symmetry).
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass
    p = argparse.ArgumentParser(
        description="Deterministic handoff report generated from the GOAL.json ledger")
    p.add_argument("--goal", type=Path, default=GOAL_DEFAULT)
    p.add_argument("--events", type=Path, default=None,
                   help="events.jsonl path (default: next to the ledger)")
    p.add_argument("--json", action="store_true")
    p.add_argument("--max-events", type=int, default=5)
    args = p.parse_args()

    if not args.goal.is_file():
        die(f"goal ledger not found: {args.goal}")
    try:
        goal = json.loads(args.goal.read_text(encoding="utf-8"))
    except Exception as e:
        die(f"{args.goal}: not valid JSON ({e})")

    events_path = args.events or (args.goal.parent / "events.jsonl")
    report = build(goal, load_events(events_path, args.max_events))

    if args.json:
        slim = {k: v for k, v in report.items() if k != "units"}
        slim["units"] = [{"id": u.get("id"), "status": u.get("status")}
                         for u in report["units"]]
        print(json.dumps(slim, ensure_ascii=False, indent=2))
    else:
        print(render_markdown(report))
    return 0


if __name__ == "__main__":
    sys.exit(main())
