#!/usr/bin/env python3
"""Goal handoff-reporter — deterministic session summary FROM the ledger (v1.45.0).

Closes the walkinglabs feature-list component «репортёр handoff»: the shift
report is GENERATED by the harness from .itd-memory/GOAL.json (+ unit events in
events.jsonl), not composed by the model from conversation memory. /handoff and
/session-save paste this output verbatim into their artifacts; the model may add
prose AROUND it but never replaces the numbers.

Report contents (all derived, zero free-text):
  - goal, status, progress N/M verified, backpressure (open units count)
  - state distribution
  - per-unit table: id / status / criterion / evidence
  - current unit + its verificationCommand (the receiving session's first move)
  - last unit events from events.jsonl (audit trail, actor included)

Ships inside the skill (skills/goal/scripts/). Stdlib only.

Usage:
  itd_goal_report.py [--goal PATH] [--events PATH] [--json] [--max-events N]

Exit codes: 0 report printed, 2 ledger missing/invalid.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

GOAL_DEFAULT = Path(".itd-memory") / "GOAL.json"
OPEN_STATUSES = ("pending", "in_progress", "recovery_required", "blocked")
CRIT_MAX = 70
EVID_MAX = 60
POLICY_KEYS = (
    "mode", "maxAttemptsPerUnit", "maxWallClockSecondsPerUnit",
    "maxTokensPerSession", "freezeVerification", "requireApproach",
    "requireIndependentReview",
)
OPTIONAL_POLICY_KEYS = (
    "enforceObservedTokens", "verificationStrategy", "maxCheckpointBytes",
)


def die(msg: str) -> None:
    print(f"ERROR: {msg}")
    sys.exit(2)


def clip(s: str, n: int) -> str:
    # Pipe escaping: criterion/evidence are free text and land in a Markdown
    # table row — an unescaped "|" would split the cell and break the table.
    s = (s or "").replace("\n", " ").replace("|", "\\|").strip()
    return s if len(s) <= n else s[: n - 1] + "…"


def load_events(path: Path, max_events: int) -> list[dict]:
    if not path.is_file():
        return []
    events: list[dict] = []
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                evt = json.loads(line)
            except Exception:
                continue
            if evt.get("type") == "unit":
                events.append(evt)
    except Exception:
        return []
    return events[-max_events:]


def fingerprint(payload: dict, *, ensure_ascii: bool = True) -> str:
    raw = json.dumps(payload, ensure_ascii=ensure_ascii, sort_keys=True,
                     separators=(",", ":")).encode("utf-8")
    return "sha256:" + hashlib.sha256(raw).hexdigest()


def policy_snapshot(policy: dict) -> dict:
    keys = POLICY_KEYS + tuple(key for key in OPTIONAL_POLICY_KEYS if key in policy)
    return {key: policy.get(key) for key in keys}


def unit_fingerprint(unit: dict) -> str:
    payload = {
        "criterion": str(unit.get("criterion") or ""),
        "verificationCommand": str(unit.get("verificationCommand") or ""),
    }
    if "riskTier" in unit:
        payload["riskTier"] = str(unit.get("riskTier") or "")
    return fingerprint(payload, ensure_ascii=False)


def checker_mode(policy: dict | None, unit: dict) -> str:
    if not policy:
        return "machine_only"
    if policy.get("requireIndependentReview"):
        return "full"
    if policy.get("verificationStrategy") == "adaptive":
        return {"low": "machine_only", "medium": "targeted",
                "high": "full"}.get(str(unit.get("riskTier") or ""), "invalid")
    return "machine_only"


def oracle_is_sealed(policy: dict | None, units: list[dict]) -> bool:
    """Report sealed only when the same integrity checks as the writer pass."""
    if policy is None:
        return False
    approved = policy.get("sealedPolicy")
    sealed = str(policy.get("sealedFingerprint") or "")
    if (not isinstance(approved, dict)
            or fingerprint(approved) != sealed
            or approved != policy_snapshot(policy)):
        return False
    for unit in units:
        state = unit.get("runState")
        if (not isinstance(state, dict)
                or str(state.get("verificationFingerprint") or "")
                != unit_fingerprint(unit)):
            return False
    return True


def build(goal: dict, events: list[dict]) -> dict:
    units = [u for u in (goal.get("units") or []) if isinstance(u, dict)]
    policy = goal.get("runPolicy") if isinstance(goal.get("runPolicy"), dict) else None
    dist: dict[str, int] = {}
    for u in units:
        dist[u.get("status") or "?"] = dist.get(u.get("status") or "?", 0) + 1
    verified = dist.get("verified", 0)
    open_units = [u for u in units if u.get("status") in OPEN_STATUSES]
    current = next((u for u in units
                    if u.get("id") == (goal.get("currentUnitId") or "")), None)
    if current is None:
        current = next((u for u in units
                        if u.get("status") in ("in_progress", "recovery_required")), None)
    next_pending = next((u for u in units if u.get("status") == "pending"), None)
    return {
        "goal": goal.get("goal") or "",
        "status": goal.get("status") or "",
        "unitsTotal": len(units),
        "unitsVerified": verified,
        "backpressure": len(open_units),
        "distribution": dist,
        "units": units,
        "currentUnit": current,
        "nextPending": next_pending,
        "events": events,
        "updatedAt": goal.get("updatedAt") or "",
        "runPolicy": policy,
        "handoffState": (goal.get("handoffState")
                         if isinstance(goal.get("handoffState"), dict) else None),
        "oracleSealed": oracle_is_sealed(policy, units),
        "attemptsUsed": sum(len(u.get("attempts") or []) for u in units
                            if isinstance(u.get("attempts") or [], list)),
    }


def render_markdown(r: dict) -> str:
    out: list[str] = []
    out.append(f"## Goal report — {r['unitsVerified']}/{r['unitsTotal']} юнитов verified"
               f" [{r['status']}]")
    out.append("")
    out.append(f"**Цель:** {r['goal']}")
    out.append(f"**Обратное давление:** {r['backpressure']} открытых юнитов"
               f" (0 = цель завершена){'' if r['backpressure'] else ' ✅'}")
    dist = ", ".join(f"{k}: {v}" for k, v in sorted(r["distribution"].items()))
    out.append(f"**Состояния:** {dist}  (updatedAt: {r['updatedAt']})")
    policy = r.get("runPolicy")
    if policy:
        out.append(
            "**Bounded autonomy:** "
            f"attempts={r['attemptsUsed']} (max {policy.get('maxAttemptsPerUnit')}/unit), "
            f"wall={policy.get('maxWallClockSecondsPerUnit')}s/unit, "
            f"tokens={policy.get('maxTokensPerSession')}/host-session; "
            f"token-meter={'required' if policy.get('enforceObservedTokens') else 'host-stop'}; "
            f"oracle={'sealed' if r['oracleSealed'] else 'UNSEALED'}")
    handoff = r.get("handoffState") or {}
    if handoff.get("required") is True:
        out.append(f"**Verified-unit handoff:** REQUIRED for `{handoff.get('unitId')}`; "
                   "the next activation is locked until explicit acknowledgement.")
    out.append("")
    out.append("| Юнит | Статус | Критерий | Evidence |")
    out.append("|---|---|---|---|")
    for u in r["units"]:
        evid = (u.get("evidence") or u.get("recoveryReason")
                or u.get("blockedReason") or u.get("skippedReason") or "—")
        out.append(f"| {u.get('id')} | {u.get('status')} "
                   f"| {clip(u.get('criterion'), CRIT_MAX)} | {clip(evid, EVID_MAX)} |")
    out.append("")
    cur = r["currentUnit"]
    blocked = [u for u in r["units"] if u.get("status") == "blocked"]
    if cur is not None:
        out.append(f"**Текущий юнит:** `{cur.get('id')}` — {clip(cur.get('criterion'), CRIT_MAX)}")
        if cur.get("status") == "recovery_required":
            out.append("**Первое действие принимающей сессии:** показать checkpoint и "
                       f"возобновить только явно: `itd_goal_verify.py --activate "
                       f"{cur.get('id')} --reason \"…\"`.")
        else:
            out.append(f"**Первое действие принимающей сессии:** прогнать "
                       f"`{cur.get('verificationCommand')}` (должен быть red), затем чинить до green.")
        deadline = cur.get("deadlineState") or {}
        if deadline.get("profile") == "working_deadline":
            out.append("**Working deadline:** "
                       f"cycle={deadline.get('cycle')}, "
                       f"hostElapsed={deadline.get('hostObservedElapsedSeconds')}s, "
                       f"checkpoint={'yes' if deadline.get('softCheckpointAt') else 'no'}, "
                       f"stopReason=`{deadline.get('stopReason') or '—'}`")
            checkpoint = deadline.get("checkpoint") or {}
            if checkpoint:
                out.append("**Checkpoint:** "
                           f"ready={checkpoint.get('ready')}; "
                           f"blocker={checkpoint.get('blocker')}; "
                           f"remainder={checkpoint.get('remainder')}; "
                           f"estimate={checkpoint.get('estimate')}")
        if policy:
            out.append(f"**Попытки текущего юнита:** {len(cur.get('attempts') or [])}; "
                       f"stopReason: `{(cur.get('runState') or {}).get('stopReason') or '—'}`")
            out.append(f"**Verification cost:** risk=`{cur.get('riskTier') or 'legacy'}`, "
                       f"checker=`{checker_mode(policy, cur)}`")
    elif r["nextPending"] is not None:
        np = r["nextPending"]
        if handoff.get("required") is True:
            out.append(f"**Следующий юнит заблокирован handoff:** сначала "
                       f"`itd_goal_verify.py --ack-handoff {handoff.get('unitId')} "
                       f"--reason \"host/user-turn provenance\"`.")
        else:
            out.append(f"**Следующий юнит:** `{np.get('id')}` — {clip(np.get('criterion'), CRIT_MAX)}"
                       f" (активировать: `itd_goal_verify.py --activate {np.get('id')}`)")
    elif handoff.get("required") is True:
        out.append(f"**Goal close заблокирован handoff:** сначала "
                   f"`itd_goal_verify.py --ack-handoff {handoff.get('unitId')} "
                   f"--reason \"host/user-turn provenance\"`.")
    elif blocked:
        # blocked units ARE open — the goal is NOT closeable, do not suggest it.
        reasons = "; ".join(f"`{u.get('id')}` — {clip(u.get('blockedReason'), EVID_MAX)}"
                            for u in blocked)
        out.append(f"**Все открытые юниты заблокированы:** {reasons}. "
                   f"Разблокировка: `itd_goal_verify.py --activate <id>`; "
                   "закрывать цель нельзя, пока блокеры не сняты.")
    else:
        out.append("**Открытых юнитов нет** — закрыть цель (`status: done`).")
    if r["events"]:
        out.append("")
        out.append("<details><summary>Последние unit-события (events.jsonl)</summary>")
        out.append("")
        for e in r["events"]:
            out.append(f"- {e.get('at')} [{e.get('actor')}] {e.get('name')}: "
                       f"{e.get('decision')} — {clip(e.get('evidence'), EVID_MAX)}")
        out.append("")
        out.append("</details>")
    return "\n".join(out)


def clip_bytes(value: object, limit: int) -> str:
    text = str(value or "").replace("\r", " ").replace("\n", " ").strip()
    raw = text.encode("utf-8")
    if len(raw) <= limit:
        return text
    return raw[:max(0, limit - 3)].decode("utf-8", errors="ignore") + "…"


def render_compact(r: dict) -> str:
    """Render a bounded delta checkpoint, never the conversation history."""
    policy = r.get("runPolicy") or {}
    limit = int(policy.get("maxCheckpointBytes") or 4096)
    limit = min(4096, max(1024, limit))
    verified = [u for u in r["units"] if u.get("status") == "verified"][-2:]
    blocked = [u for u in r["units"]
               if u.get("status") in ("blocked", "recovery_required")][:2]
    current = r.get("currentUnit") or r.get("nextPending")
    evidence = [f"- {clip_bytes(u.get('id'), 48)}: "
                f"{clip_bytes(u.get('evidence') or 'verified', 140)}"
                for u in verified] or ["- none yet"]
    def compact_risk(unit: dict) -> str:
        detail = str(unit.get("recoveryReason") or unit.get("blockedReason") or "blocked")
        checkpoint = (unit.get("deadlineState") or {}).get("checkpoint") or {}
        if checkpoint:
            detail += (f"; ready={checkpoint.get('ready')}; "
                       f"blocker={checkpoint.get('blocker')}; "
                       f"remainder={checkpoint.get('remainder')}; "
                       f"estimate={checkpoint.get('estimate')}")
        return f"- {clip_bytes(unit.get('id'), 48)}: {clip_bytes(detail, 320)}"

    risks = [compact_risk(u) for u in blocked] or ["- none"]
    handoff = r.get("handoffState") or {}
    if handoff.get("required") is True:
        nxt = (f"- acknowledge handoff for {clip_bytes(handoff.get('unitId'), 48)} "
               "before activating another unit or closing the goal")
    elif current:
        if current.get("status") == "recovery_required":
            nxt = (f"- resume {clip_bytes(current.get('id'), 48)} only with "
                   "--activate --reason after checkpoint handoff")
        else:
            nxt = (f"- {clip_bytes(current.get('id'), 48)} "
                   f"[{checker_mode(policy, current)}]: "
                   f"{clip_bytes(current.get('verificationCommand'), 320)}")
    else:
        nxt = "- close goal; no open unit"
    out = [
        "# Goal checkpoint",
        "",
        "Done",
        f"- {r['unitsVerified']}/{r['unitsTotal']} units verified",
        "",
        "Evidence",
        *evidence,
        "",
        "Status",
        f"- goal={clip_bytes(r['status'], 40)}; backpressure={r['backpressure']}; "
        f"current={clip_bytes((r.get('currentUnit') or {}).get('id') or 'none', 48)}; "
        f"handoff={'required' if (r.get('handoffState') or {}).get('required') else 'clear'}",
        "",
        "Open risks",
        *risks,
        "",
        "Next",
        nxt,
    ]
    text = "\n".join(out)
    if len(text.encode("utf-8")) > limit:
        out = [
            "# Goal checkpoint", "", "Done",
            f"- {r['unitsVerified']}/{r['unitsTotal']} units verified", "",
            "Evidence", "- see GOAL.json", "", "Status",
            f"- goal={clip_bytes(r['status'], 40)}; backpressure={r['backpressure']}", "",
            "Open risks", f"- blocked={len(blocked)}", "", "Next", nxt,
        ]
        text = "\n".join(out)
    if len(text.encode("utf-8")) > limit:
        die(f"compact checkpoint exceeds sealed {limit}-byte limit")
    return text


def main() -> int:
    # Windows consoles default to cp125x — reconfigure so the Russian report
    # never raises UnicodeEncodeError (platform symmetry).
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            pass
    p = argparse.ArgumentParser(
        description="Deterministic handoff report generated from the GOAL.json ledger")
    p.add_argument("--goal", type=Path, default=GOAL_DEFAULT)
    p.add_argument("--events", type=Path, default=None,
                   help="events.jsonl path (default: next to the ledger)")
    p.add_argument("--json", action="store_true")
    p.add_argument("--compact", action="store_true",
                   help="bounded Done/Evidence/Status/Open risks/Next checkpoint")
    p.add_argument("--max-events", type=int, default=5)
    args = p.parse_args()

    if not args.goal.is_file():
        die(f"goal ledger not found: {args.goal}")
    try:
        goal = json.loads(args.goal.read_text(encoding="utf-8"))
    except Exception as e:
        die(f"{args.goal}: not valid JSON ({e})")

    events_path = args.events or (args.goal.parent / "events.jsonl")
    report = build(goal, load_events(events_path, args.max_events))

    if args.json and args.compact:
        die("--json and --compact are mutually exclusive")
    if args.json:
        slim = {k: v for k, v in report.items() if k != "units"}
        slim["units"] = [{"id": u.get("id"), "status": u.get("status"),
                          "riskTier": u.get("riskTier") or "legacy",
                          "checkerMode": checker_mode(report.get("runPolicy"), u),
                          "attempts": len(u.get("attempts") or []),
                          "stopReason": (u.get("runState") or {}).get("stopReason") or "",
                          "deadlineStopReason": (u.get("deadlineState") or {}).get("stopReason") or "",
                          "deadlineElapsedSeconds": (u.get("deadlineState") or {}).get(
                              "hostObservedElapsedSeconds"),
                          "deadlineCycle": (u.get("deadlineState") or {}).get("cycle"),
                          "deadlineCheckpoint": (u.get("deadlineState") or {}).get(
                              "checkpoint") or {}}
                         for u in report["units"]]
        print(json.dumps(slim, ensure_ascii=False, indent=2))
    elif args.compact:
        print(render_compact(report))
    else:
        print(render_markdown(report))
    return 0


if __name__ == "__main__":
    sys.exit(main())
